//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ham2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class H264 : global::System.Configuration.ApplicationSettingsBase {
        
        private static H264 defaultInstance = ((H264)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new H264())));
        
        public static H264 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int crf {
            get {
                return ((int)(this["crf"]));
            }
            set {
                this["crf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("veryfast")]
        public string preset {
            get {
                return ((string)(this["preset"]));
            }
            set {
                this["preset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96k")]
        public string videoBitRate {
            get {
                return ((string)(this["videoBitRate"]));
            }
            set {
                this["videoBitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("198k")]
        public string buffersize {
            get {
                return ((string)(this["buffersize"]));
            }
            set {
                this["buffersize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int gop {
            get {
                return ((int)(this["gop"]));
            }
            set {
                this["gop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aac")]
        public string audioCodec {
            get {
                return ((string)(this["audioCodec"]));
            }
            set {
                this["audioCodec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24k")]
        public string audioBitRate {
            get {
                return ((string)(this["audioBitRate"]));
            }
            set {
                this["audioBitRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yuv420p")]
        public string pixelFormat {
            get {
                return ((string)(this["pixelFormat"]));
            }
            set {
                this["pixelFormat"] = value;
            }
        }
    }
}
